import 'dart:io';

import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:temple_adventures_admin/features/offers/models/offer.model.dart';
import '../../../database/enums/supabase_tables.enum.dart';
import '../../../services/logging.dart';

/// Repository for offer-related database operations.
/// 
/// Handles CRUD operations for offers, including offer creation, updates, image uploads,
/// and deletion. Offers represent promotional deals, discounts, or special packages
/// that can be displayed to customers.
class OffersRepository {
  OffersRepository();

  final SupabaseClient supabase = Supabase.instance.client;

  /// Adds a new offer or updates an existing one.
  /// 
  /// **Logic:**
  /// - If `offer.id` is not null → Updates existing offer
  /// - If `offer.id` is null → Inserts new offer
  /// 
  /// **Data Transformation:**
  /// - For updates: Uses `removeId: false` to include ID in the update
  /// - For inserts: ID is excluded (database will auto-generate)
  /// 
  /// **Use Case**: Creating or updating promotional offers, discounts, or special packages.
  /// Offers can include images, descriptions, validity periods, and pricing information.
  Future<void> addUpdateOffer({required Offer offer}) async {
    if (offer.id != null) {
      // Update existing offer entry
      await supabase.from(SupabaseTable.offers.toValue()).update(offer.toRow(removeId: false)).eq('id', offer.id!);
    } else {
      // Insert new offer entry (ID will be auto-generated by database)
      await supabase.from(SupabaseTable.offers.toValue()).insert(offer.toRow());
    }
  }

  /// Fetches all offers from the database.
  /// 
  /// **Query Details:**
  /// - Uses Supabase's join syntax to fetch related user data:
  ///   - `created_by`: User who created the offer
  /// - Orders results by `created_at` (ascending, oldest offers first)
  /// 
  /// **Returns**: List of all offers with their creator information, ordered chronologically.
  /// 
  /// **Note**: Offers are ordered by creation time to show the oldest offers first.
  /// This can be useful for displaying offers in the order they were created.
  /// 
  /// **Use Case**: Used to populate offer lists, promotional displays, and admin screens
  /// for managing offers.
  Future<List<Offer>> fetchAllOffers() async {
    final response = await supabase
        .from(SupabaseTable.offers.toValue())
        .select('''
          *,
          created_by:users!offers_created_by_id_fkey (*)
        ''')
        .order('created_at', ascending: true);

    // Transform database response to Offer model objects
    return (response as List<dynamic>).map((item) => OfferMapper.fromMap(item as Map<String, dynamic>)).toList();
  }

  /// Uploads an offer image to Supabase storage.
  /// 
  /// **Process:**
  /// 1. Read image file as bytes
  /// 2. Generate unique filename using current timestamp
  /// 3. Upload to Supabase storage bucket `offers`
  /// 4. Get and return the public URL for the uploaded image
  /// 
  /// **Parameters:**
  /// - `imageFile`: The image file to upload
  /// 
  /// **Returns**: The public URL of the uploaded image, or null if upload failed.
  /// 
  /// **File Naming:**
  /// - Uses timestamp in milliseconds as filename to ensure uniqueness
  /// - Always uses `.jpg` extension regardless of original file format
  /// 
  /// **Storage Options:**
  /// - Uses `upsert: true` to overwrite if file with same name exists (shouldn't happen with timestamp)
  /// 
  /// **Use Case**: Upload promotional images when creating or editing offers.
  /// The returned URL can be stored in the offer record for display in the UI.
  Future<String?> uploadImage(File imageFile) async {
    try {
      // Read image file as bytes
      final bytes = await imageFile.readAsBytes();
      
      // Generate unique filename using timestamp
      final fileName = '${DateTime.now().millisecondsSinceEpoch}.jpg';
      
      // Upload to Supabase storage
      await supabase.storage
          .from(SupabaseTable.offers.toValue())
          .uploadBinary(fileName, bytes, fileOptions: FileOptions(upsert: true));
      
      // Get public URL for the uploaded image
      final publicUrl = supabase.storage.from(SupabaseTable.offers.toValue()).getPublicUrl(fileName);
      Log.i("Image uploaded successfully: $publicUrl");
      return publicUrl;
    } catch (e, stack) {
      Log.e("Upload failed: $e", error: e, stackTrace: stack);
      return null;
    }
  }

  /// Deletes an offer from the database.
  /// 
  /// **Process:**
  /// - Performs a hard delete (permanently removes the offer record)
  /// 
  /// **Parameters:**
  /// - `offerId`: Offer ID to delete
  /// **Note**: This is a hard delete - the offer record will be permanently removed.
  /// **Use Case**: Removing offers that are no longer valid or needed.
  Future<void> deleteOffer(int offerId) async {
    try {
      // Hard delete: permanently remove offer from database
      await supabase.from(SupabaseTable.offers.toValue()).delete().eq('id', offerId);
      Log.i('Deleted offer with ID: $offerId');
    } catch (e, stack) {
      // Log error but don't rethrow - allows operation to fail silently
      Log.e('Error deleting offer', error: e, stackTrace: stack);
    }
  }
}
