import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:temple_adventures_admin/features/roster/models/customer_feedback.model.dart';
import 'package:temple_adventures_admin/features/roster/models/dsd_customer.model.dart';
import '../../../database/enums/supabase_tables.enum.dart';
import '../models/roster.model.dart';

/// Repository for roster-related database operations.
/// 
/// Handles CRUD operations for roster entries, customer feedback, and DSD (Discover Scuba Diving) customers.
/// Manages staff roster scheduling and customer feedback tracking.
class RosterRepository {
  RosterRepository();

  final SupabaseClient supabase = Supabase.instance.client;

  /// Adds a new roster entry or updates an existing one.
  /// 
  /// **Logic:**
  /// - If `roster.id` is not null → Updates existing roster entry
  /// - If `roster.id` is null → Inserts new roster entry
  /// 
  /// **Data Transformation:**
  /// - For updates: Uses `removeId: false` to include ID in the update
  /// - For inserts: ID is excluded (database will auto-generate)
  /// 
  /// **Use Case**: Creating or updating staff roster entries for specific dates.
  /// Rosters track staff assignments, schedules, and availability.
  Future<void> addUpdateRoster({required Roster roster}) async {
    if (roster.id != null) {
      // Update existing roster entry
      await supabase.from(SupabaseTable.roster.toValue()).update(roster.toRow(removeId: false)).eq('id', roster.id!);
    } else {
      // Insert new roster entry (ID will be auto-generated by database)
      await supabase.from(SupabaseTable.roster.toValue()).insert(roster.toRow());
    }
  }

  /// Adds a new customer feedback entry or updates an existing one.
  /// 
  /// **Logic:**
  /// - If `customerFeedback.id` is not null → Updates existing feedback entry
  /// - If `customerFeedback.id` is null → Inserts new feedback entry
  /// 
  /// **Data Transformation:**
  /// - For updates: Uses `removeId: false` to include ID in the update
  /// - For inserts: ID is excluded (database will auto-generate)
  /// 
  /// **Use Case**: Recording or updating customer feedback for services/activities.
  /// Feedback can include ratings, comments, and other customer satisfaction metrics.
  Future<void> addUpdateCustomerFeedback({required CustomerFeedback customerFeedback}) async {
    if (customerFeedback.id != null) {
      // Update existing customer feedback entry
      await supabase
          .from(SupabaseTable.customerFeedback.toValue())
          .update(customerFeedback.toRow(removeId: false))
          .eq('id', customerFeedback.id!);
    } else {
      // Insert new customer feedback entry (ID will be auto-generated by database)
      await supabase.from(SupabaseTable.customerFeedback.toValue()).insert(customerFeedback.toRow());
    }
  }

  /// Fetches all DSD (Discover Scuba Diving) customers for a specific date.
  /// 
  /// **Query Details:**
  /// - Uses `dsd_customers` view which includes roster and feedback information
  /// - Filters by `dive_date` matching the provided date
  /// 
  /// **Parameters:**
  /// - `date`: The dive date to filter by (format should match database date format)
  /// 
  /// **Returns**: List of DSD customers with their associated roster and feedback data.
  /// 
  /// **Use Case**: Displaying DSD customer information for a specific date, including
  /// their roster assignments and any feedback they've provided.
  Future<List<DSDCustomer>> getAllDSDCustomersWithRosterAndFeedback(String date) async {
    // Query DSD customers for the specified date
    final response = await supabase.from('dsd_customers').select().eq('dive_date', date);

    // Transform database response to DSDCustomer model objects
    List<DSDCustomer> customers = response.map((data) => DSDCustomerMapper.fromMap(data)).toList();

    return customers;
  }
}
